version: "3.8"

services:
  st-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: st-open-source-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Server Configuration
      - NODE_ENV=development
      - PORT=3000
      - VERSION=0.1.0

      # Database Configuration (Neon)
      - DATABASE_URL=postgresql://neondb_owner:npg_DXwn1qMV2pUL@ep-old-lake-a2g1hp06-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

      # Security
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-minimum-32-characters
      - JWT_EXPIRES_IN=7d

      # Rate Limiting
      - RATE_LIMIT_POINTS=500
      - RATE_LIMIT_DURATION=120

      # Request Limits
      - MAX_REQUEST_SIZE=10mb

      # Logging
      - LOG_LEVEL=info
      - TEST_DATA=true
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  st_logs:
    driver: local
  st_uploads:
    driver: local

networks:
  app_network:
    driver: bridge
